{% set name = "kosh" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: "3.4"

source:
  url: https://github.com/LLNL/kosh/archive/v{{ version }}.tar.gz
  sha256: 10d6a94d90efb941d22f1c81601a0134827f0c96d732fb02d71b5aa89f11a5e3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - llnl-sina >=1.14.0
    - networkx >=2.6
    - numpy
    - matplotlib-base
    - scipy
    - h5py >=3
    - scikit-learn >=1.0.2
    - pandas
    - hdbscan
    - tqdm
    - cython <3
    - filelock
  run:
    - python >={{ python_min }}
    - llnl-sina >=1.14.0
    - networkx >=2.6
    - numpy
    - matplotlib-base
    - scipy
    - h5py >=3
    - scikit-learn >=1.0.2
    - pandas
    - hdbscan
    - tqdm
    - cython <3
    - filelock

test:
  imports:
    - kosh
  commands:
    - pip check
    - kosh --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LLNL/kosh
  summary: Kosh allows codes to store, query, share and manipulate data via an easy-to-use Python API. Kosh lies on top of Sina and as a result can use any database backend supported by Sina. In adition Kosh aims to make data access and sharing as simple as possible.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - doutriaux1
